name: Deploy to Azure Functions

on:
  push:
    branches: [ feature/market_data_integration ]
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
  PYTHON_VERSION: '3.12'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r src/requirements.txt

    - name: Run database migrations
      env:
        POSTGRES_CONN_STRING: ${{ secrets.POSTGRES_CONN_STRING }}
      run: |
        python src/database/migrate.py

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Package function
      run: |
        cd src && zip -r ../deployment.zip *

    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: wasit-market-trend.scm
        package: deployment.zip

    - name: Verify deployment
      run: |
        curl -s "https://wasit-market-trend.scm.azurewebsites.net/" | j